language: python
python:
  - "3.4"
  - "3.5"
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install .[dev]
# command to run tests
script:
  - coverage run --parallel-mode -m pytest --capture=no  -v
  - coverage combine
  - coverage xml
  - coverage report --fail-under=100
after_success:
  - coveralls
